Repository iMicknl/ha-sagemcom-fast, pull requests merged in 2022-02, with the labels that each got.

#18 Add SSL support
  custom_components/sagemcom_fast/__init__.py
  custom_components/sagemcom_fast/config_flow.py
  custom_components/sagemcom_fast/strings.json
  custom_components/sagemcom_fast/translations/en.json
Labels: feature

#30 Log out of Sagemcom client after every query
  custom_components/sagemcom_fast/__init__.py
  custom_components/sagemcom_fast/config_flow.py
  custom_components/sagemcom_fast/device_tracker.py
Labels: feature

#37 Fix reboot functionality
  custom_components/sagemcom_fast/__init__.py
Labels: enhancement

#40 Bump python-sagemcom-api version to 1.0.8
  custom_components/sagemcom_fast/manifest.json
Labels: enhancement

#42 Updates for readme.md
  README.md
Labels: exclude-from-changelog
